FROM python:3.11.7-slim

WORKDIR /code

ARG STREAMLIT_IP
ARG STREAMLIT_PORT

COPY ift6758/ ./ift6758
COPY streamlit_app.py ./streamlit_app.py

RUN pip install -r ./ift6758/requirements.txt
RUN pip install -e ./ift6758
RUN pip install streamlit

EXPOSE ${STREAMLIT_PORT}

CMD streamlit run ./streamlit_app.py --server.port ${STREAMLIT_PORT} --server.address ${STREAMLIT_IP}
