# docker-compose.yaml
version: '4'

services:
  serving:
    build:
      context: ./
      dockerfile: Dockerfile.serving
      args:
        SERVING_PORT: 5000
        SERVING_IP: 0.0.0.0
    image: ift6758/serving:latest
    ports:
      - "5000:5000"
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      - FLASK_LOG=flask.log

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - "5001:5001"
    environment:
      - STREAMLIT_IP=0.0.0.0
      - STREAMLIT_PORT=5001
      

     
