FROM python:3.11.7-slim

WORKDIR /code

ARG SERVING_IP
ARG SERVING_PORT

COPY ift6758/ /code/ift6758/

RUN pip install -r ./ift6758/requirements.txt
RUN pip install -e ./ift6758

COPY serving/ ./serving

EXPOSE ${SERVING_PORT}

CMD gunicorn --bind ${SERVING_IP}:${SERVING_PORT} serving.app:app
